name: DartWiseBot
description: The Wise Bot reborn.
# version: 1.0.0
# homepage: https://github.com/DinoLeung/DartWiseBot/
# author: dinoleung <dino@330z.net>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  teledart: ^0.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
