name: DartWiseBot
description: The Wise Bot reborn.
# version: 1.0.0
# homepage: https://github.com/DinoLeung/DartWiseBot/
# author: dinoleung <dino@330z.net>

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  aws_lambda_dart_runtime: ^1.1.0
  teledart: ^0.3.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
