name: DartWiseBot
description: The Wise Bot reborn.
# version: 1.0.0
# homepage: https://github.com/DinoLeung/DartWiseBot/
# author: dinoleung <dino@330z.net>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  teledart: ^0.0.39

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.5
