name: DartWiseBot
description: The Wise Bot reborn.
# version: 1.0.0
# homepage: https://www.example.com
# author: dinoleung <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  teledart: ^0.0.26

dev_dependencies:
  pedantic: ^1.1.0
  test: ^1.0.0
