name: DartWiseBot
description: The Wise Bot reborn.
# version: 1.0.0
# homepage: https://github.com/DinoLeung/DartWiseBot/
# author: dinoleung <dino@330z.net>

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  teledart: ^0.5.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
